<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="LagoVista.Core.Networking" Version="7.0.2" />
    <PackageVersion Include="LagoVista.Core.TestBase" Version="7.0.2" />
    <PackageVersion Include="LagoVista.IoT.Deployment.Admin" Version="7.0.1" />
    <PackageVersion Include="LagoVista.IoT.Deployment.Models" Version="7.0.1" />
    <PackageVersion Include="LagoVista.IoT.DeviceAdmin.Models" Version="7.0.1" />
    <PackageVersion Include="LagoVista.IoT.DeviceManagement.Core" Version="7.0.1" />
    <PackageVersion Include="LagoVista.IoT.DeviceMessaging.Models" Version="7.0.1" />
    <PackageVersion Include="LagoVista.IoT.Pipeline.Admin" Version="7.0.1" />
    <PackageVersion Include="LagoVista.MediaServices.Models" Version="7.0.2" />
  </ItemGroup>
</Project>
